<?php
/**
 * Created by PhpStorm.
 * User: zhangjun
 * Date: 05/09/2018
 * Time: 2:27 PM
 */

class Plugin_GifController extends  HttpBaseController
{
    public  function doIndex()
    {
//        parent::doIndex(); // TODO: Change the autogenerated stub
        $this->index();
    }


    public function index()
    {
        header('Access-Control-Allow-Origin: *');
        $method = $_SERVER['REQUEST_METHOD'];
        if ($method == 'POST') {
        } else {
            $params['gifs'] = [
                [
                    "url" => "https://media.giphy.com/media/NWLUwtaivTes8/200w_d.gif",
                    "width" => 200,
                    "height" => 200
                ],
                [
                    "url" => "https://media.giphy.com/media/NWLUwtaivTes8/200w_d.gif",
                    "width" => 200,
                    "height" => 200
                ],
                [
                    "url" => "https://media.giphy.com/media/NWLUwtaivTes8/200w_d.gif",
                    "width" => 200,
                    "height" => 200
                ],
                [
                    "url" => "https://media.giphy.com/media/NWLUwtaivTes8/200w_d.gif",
                    "width" => 200,
                    "height" => 200
                ],
                [
                    "url" => "https://media.giphy.com/media/NWLUwtaivTes8/200w_d.gif",
                    "width" => 200,
                    "height" => 200
                ],[
                    "url" => "https://media.giphy.com/media/NWLUwtaivTes8/200w_d.gif",
                    "width" => 200,
                    "height" => 200
                ],[
                    "url" => "https://media.giphy.com/media/NWLUwtaivTes8/200w_d.gif",
                    "width" => 200,
                    "height" => 200
                ],[
                    "url" => "https://media.giphy.com/media/NWLUwtaivTes8/200w_d.gif",
                    "width" => 200,
                    "height" => 200
                ],[
                    "url" => "https://media.giphy.com/media/NWLUwtaivTes8/200w_d.gif",
                    "width" => 200,
                    "height" => 200
                ],[
                    "url" => "https://media.giphy.com/media/NWLUwtaivTes8/200w_d.gif",
                    "width" => 200,
                    "height" => 200
                ],[
                    "url" => "https://media.giphy.com/media/NWLUwtaivTes8/200w_d.gif",
                    "width" => 200,
                    "height" => 200
                ],[
                    "url" => "https://media.giphy.com/media/NWLUwtaivTes8/200w_d.gif",
                    "width" => 200,
                    "height" => 200
                ],[
                    "url" => "https://media.giphy.com/media/NWLUwtaivTes8/200w_d.gif",
                    "width" => 200,
                    "height" => 200
                ],[
                    "url" => "https://media.giphy.com/media/NWLUwtaivTes8/200w_d.gif",
                    "width" => 200,
                    "height" => 200
                ],[
                    "url" => "https://media.giphy.com/media/NWLUwtaivTes8/200w_d.gif",
                    "width" => 200,
                    "height" => 200
                ],[
                    "url" => "https://media.giphy.com/media/NWLUwtaivTes8/200w_d.gif",
                    "width" => 200,
                    "height" => 200
                ],[
                    "url" => "https://media.giphy.com/media/NWLUwtaivTes8/200w_d.gif",
                    "width" => 200,
                    "height" => 200
                ],[
                    "url" => "https://media.giphy.com/media/NWLUwtaivTes8/200w_d.gif",
                    "width" => 200,
                    "height" => 200
                ],[
                    "url" => "https://media.giphy.com/media/NWLUwtaivTes8/200w_d.gif",
                    "width" => 200,
                    "height" => 200
                ],[
                    "url" => "https://media.giphy.com/media/NWLUwtaivTes8/200w_d.gif",
                    "width" => 200,
                    "height" => 200
                ],[
                    "url" => "https://media.giphy.com/media/NWLUwtaivTes8/200w_d.gif",
                    "width" => 200,
                    "height" => 200
                ],
            ];
            $params['gifs'] = json_encode($params['gifs']);
            echo $this->display("plugin_index", $params);
            return;
        }
    }
}