<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_site_login.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>site.ApiSiteLoginResponse</code>
 */
class ApiSiteLoginResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string sessionId = 1;</code>
     */
    private $sessionId = '';
    /**
     * Generated from protobuf field <code>.core.AllUserProfile profile = 2;</code>
     */
    private $profile = null;

    public function __construct() {
        \GPBMetadata\Site\ApiSiteLogin::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string sessionId = 1;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->sessionId;
    }

    /**
     * Generated from protobuf field <code>string sessionId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->sessionId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.core.AllUserProfile profile = 2;</code>
     * @return \Zaly\Proto\Core\AllUserProfile
     */
    public function getProfile()
    {
        return $this->profile;
    }

    /**
     * Generated from protobuf field <code>.core.AllUserProfile profile = 2;</code>
     * @param \Zaly\Proto\Core\AllUserProfile $var
     * @return $this
     */
    public function setProfile($var)
    {
        GPBUtil::checkMessage($var, \Zaly\Proto\Core\AllUserProfile::class);
        $this->profile = $var;

        return $this;
    }

}

