<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_platform_login.proto

namespace Zaly\Proto\Platform;

/**
 * Protobuf enum <code>Platform\LoginUserType</code>
 */
class LoginUserType
{
    /**
     * Generated from protobuf enum <code>UserTypeInvalid = 0;</code>
     */
    const UserTypeInvalid = 0;
    /**
     *register, display userInfo
     *
     * Generated from protobuf enum <code>UserTypeResiter = 1;</code>
     */
    const UserTypeResiter = 1;
    /**
     *loginer, don't display userInfo
     *
     * Generated from protobuf enum <code>UserTypeLoginer = 2;</code>
     */
    const UserTypeLoginer = 2;
}

